apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-service
spec:
  selector:
    app: docker-k8s
  ports:
  - protocol: "TCP"
    port: 8090
    targetPort: 8090
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s
spec:
  selector:
    matchLabels:
      app: docker-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: docker-k8s
    spec:
      containers:
      - name: docker-k8s
        image: ad1989/docker-k8s:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090